GET http://localhost:3000/posts
Accept: application/json

###
POST http://localhost:3000/posts
Content-Type:application/json

{
 "name":"johns",
 "description":"hi"
}

###
GET http://localhost:3000/posts/b2ab3517-2250-44ce-85d0-e3d2286c0914
Accept: application/json


###
PUT http://localhost:3000/posts/b2ab3517-2250-44ce-85d0-e3d2286c0914
Content-Type:application/json

{
  "name":"johnny",
  "description":"hello"
}

###
DELETE http://localhost:3000/posts/2b71b96a-413a-494f-b19a-9b3aa4c5a90d

###
HEAD http://localhost:3000/posts





