GET http://localhost:3001/posts
Accept: application/json

###
POST http://localhost:3001/posts
Content-Type:application/json

{
 "name":"john",
 "description":"hihi"
}

###
GET http://localhost:3000/posts/e062bd74-a9a7-4b3a-a16c-713551d73518
Accept: application/json


###
PUT http://localhost:3000/posts/e062bd74-a9a7-4b3a-a16c-713551d73518
Content-Type:application/json

{
  "name":"arosh",
  "description":"hello"
}

###
DELETE http://localhost:3001/posts/2

###
HEAD http://localhost:3000/posts





